export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';
export const EXPENSE_MONTH = 'EXPENSE_MONTH';
export const EXPENSE_YEAR = 'EXPENSE_YEAR';
export const EXPENSE_WEEK = 'EXPENSE_WEEK';
export const EXPENSE_CATEGORY_MONTH = 'EXPENSE_CATEGORY_MONTH';
export const EXPENSE_CATEGORY_YEAR = 'EXPENSE_CATEGORY_YEAR';
export const EXPENSE_CATEGORY_WEEK = 'EXPENSE_CATEGORY_WEEK';

